### ISSUE TITLE
Deprecation Warning when run demo code

### ISSUE THREAD

**Issue by djsg** [tus/tus-node-server#110]
When I run

DEBUG=* npm run demo

I got the following warning:

(node:20367) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

My npm version is 5.6.0
node -v output: v10.1.0

**Comment by Acconut** [comment]
Thanks for the details! Could you also please run `DEBUG=* --trace-warnings node demo/server.js`? This should also provide the line where the deprecation warning is triggered. Since I could not find a direct usage of Buffer in tus-node-server, it's likely in one of its dependencies.

**Comment by djsg** [comment]
The following is the output: same as before

node-server$ DEBUG=* node demo/server.js --trace-warnings
[16:03:01] tus server listening at http://127.0.0.1:9000 using FileStore
  tus-node-server [TusServer] handle: GET /files/ +0ms
  tus-node-server [TusServer] handle: OPTIONS /files/ +12s
  tus-node-server [TusServer] handle: POST /files/ +7ms
  tus-node-server [TusServer] handle: OPTIONS /files/78d84f2d10a6c3856bef365ac49e8cb8 +14ms
  tus-node-server [TusServer] handle: PATCH /files/78d84f2d10a6c3856bef365ac49e8cb8 +11ms
  tus-node-server:stores:filestore [FileStore] write: 11383 bytes written to files/78d84f2d10a6c3856bef365ac49e8cb8 +0ms
  tus-node-server:stores:filestore [FileStore] write: File is now 11383 bytes +0ms
[16:05:19] [EVENT HOOK] Upload complete for file 78d84f2d10a6c3856bef365ac49e8cb8
upload success!
(node:24203) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

DEBUG=* --trace-warnings node demo/server.js does not work. 
I got "--trace-warnings: command not found" error.

**Comment by Acconut** [comment]
Sorry, I mixed up the order. It should be `DEBUG=* node --trace-warnings demo/server.js`. The `--tract-warnings` must be directly after node or otherwise it will not be recognized by node.

**Comment by djsg** [comment]
(node:3526) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:159:11)
    at new Buffer (buffer.js:174:3)
    at keyValuePairList.reduce (/home/user/Code/fitpu/AI_oncologist/server_code/laravel/public/uploads/tus_server/tus-node-server/demo/server.js:64:21)
    at Array.reduce (<anonymous>)
    at metadataStringToObject (/home/user/Code/fitpu/AI_oncologist/server_code/laravel/public/uploads/tus_server/tus-node-server/demo/server.js:62:27)
    at FileStore.server.on (/home/user/Code/fitpu/AI_oncologist/server_code/laravel/public/uploads/tus_server/tus-node-server/demo/server.js:77:41)
    at FileStore.emit (events.js:182:13)
    at WriteStream.req.pipe.on (/home/user/Code/fitpu/AI_oncologist/server_code/laravel/public/uploads/tus_server/tus-node-server/lib/stores/FileStore.js:129:26)
    at WriteStream.emit (events.js:187:15)
    at finishMaybe (_stream_writable.js:644:14)

**Comment by Acconut** [comment]
Good, thank you. However, the stack trace does not match the `demo/server.js` file we have in this repository (https://github.com/tus/tus-node-server/blob/master/demo/server.js). Could it be that you have local modifications for this file?

**Comment by djsg** [comment]
yeah, I added some code to rename uploaded file to its original name, which seems not a good idea after reading some posts.
I shall comment them out.

Thx.

**Comment by Acconut** [comment]
Ok, sounds good :+1:
