### ISSUE TITLE
Minio Datastore get upload offset conflict [409]

### ISSUE THREAD

**Issue by bibifitri** [tus/tus-node-server#133]
I build file uploader using following stack:
- tus-node-server
- express
- minio cloud storage

Below my index.js looks like:

```
const tus = require('tus-node-server')
const server = new tus.Server()

server.datastore = new tus.S3Store({
    path: '/files',
    bucket: 'my-bucket-name',
    accessKeyId: 'my-access-key',
    secretAccessKey: 'my-secret-key',
    region: 'eu-west-1',
    endpoint: 'http://localhost:9000',
    s3ForcePathStyle: true,
    signatureVersion: 'v2',
    partSize: 4 * 1024 * 1024
});

const express = require('express')
const app = express()
const uploadApp = express()
uploadApp.all('*', server.handle.bind(server))
app.use('/uploads', uploadApp);

const host = '127.0.0.1';
const port = 1080;
app.listen(port, host);
```

I use S3store because minio is compatible with S3 services. When I tried to upload file 50MB. I got this error 
[tus-js-client web browser]
Failed because: Error: tus: unexpected response while uploading chunk, originated from request (response code: 409, response text: Upload-Offset conflict)

[tus-node-server]
```
{ NotFound: null
    at Request.extractError (/Users/fbs/Documents/example/express-tus-minio-server/node_modules/aws-sdk/lib/services/s3.js:560:35)
    at Request.callListeners (/Users/fbs/Documents/example/express-tus-minio-server/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
    at Request.emit (/Users/fbs/Documents/example/express-tus-minio-server/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/Users/fbs/Documents/example/express-tus-minio-server/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/fbs/Documents/example/express-tus-minio-server/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/fbs/Documents/example/express-tus-minio-server/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/fbs/Documents/example/express-tus-minio-server/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/fbs/Documents/example/express-tus-minio-server/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/fbs/Documents/example/express-tus-minio-server/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/fbs/Documents/example/express-tus-minio-server/node_modules/aws-sdk/lib/sequential_executor.js:119:18)
  message: null,
  code: 'NotFound',
  region: null,
  time: 2018-10-12T07:06:23.049Z,
  requestId: '155CCAA517A55A98',
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 44.82171261258596 }
[S3Store] getOffset: No file found.
```
I have no idea how to solve this issue. Please help! 
@bhstahl @rictorres

**Comment by Acconut** [comment]
There have been a few issues with Minio in the past when using the tusd server (https://github.com/tus/tusd/issues/156) which were caused by the fact that Minio was not fully compatible with AWS S3. This problem has been fixed some time afterwards: https://github.com/minio/minio/releases/tag/RELEASE.2017-12-28T01-21-00Z

So, it's may be that this is again caused by Minio. What version of Minio are you using?

**Comment by bibifitri** [comment]
I use the latest docker image of minio. 
I have tried upload 50MB file using tusd server and minio, the process finished successfully but I encountered problem when I was uploading file using tus-node-server and minio.

**Comment by Acconut** [comment]
Unfortunately, I have little knowledge about how tus-node-server's S3Store works. Maybe @rictorres could have a look at this?

In the meantime, I would recommend you to use tusd which should be compatible with minio, as you mentioned.

**Comment by saschbro** [comment]
there is a minimum chunk size limit of 5 mb for S3. not sure if this restriction is also valid for minio. see https://github.com/tus/tus-js-client#tusdefaultoptions `chunkSize` for more information.
