### ISSUE TITLE
Unknown encoding: base64url with version 0.6.0

### ISSUE THREAD

**Issue by tomgreco** [tus/tus-node-server#247]
Using tus-js-client on client side.
On the latest version I started getting this error on every patch request. 

```
backend_1       | 2022-05-27T01:32:25.110Z tus-node-server:stores:s3store [621fc6ab24f75100564f1c19/628b88ca3d32db002ab6bfe4/H/image/c04d6e51-11be-4614-846f-f3ee44e7ab3f.621fc6ab24f75100564f1c19_1653702287033_main] retrieving metadata
backend_1       | 2022-05-27T01:32:25.110Z tus-node-server:stores:s3store [621fc6ab24f75100564f1c19/628b88ca3d32db002ab6bfe4/H/image/c04d6e51-11be-4614-846f-f3ee44e7ab3f.621fc6ab24f75100564f1c19_1653702287033_main] metadata from cache
backend_1       | 2022-05-27T01:32:25.364Z tus-node-server:stores:s3store [621fc6ab24f75100564f1c19/628b88ca3d32db002ab6bfe4/H/image/c04d6e51-11be-4614-846f-f3ee44e7ab3f.621fc6ab24f75100564f1c19_1653702287033_main] retrieving metadata
backend_1       | 2022-05-27T01:32:25.364Z tus-node-server:stores:s3store [621fc6ab24f75100564f1c19/628b88ca3d32db002ab6bfe4/H/image/c04d6e51-11be-4614-846f-f3ee44e7ab3f.621fc6ab24f75100564f1c19_1653702287033_main] metadata from cache
backend_1       | 2022-05-27T01:32:25.515Z tus-node-server:handlers:patch [PatchHandler] TypeError [ERR_UNKNOWN_ENCODING] [ERR_UNKNOWN_ENCODING]: Unknown encoding: base64url
backend_1       |     at Buffer.toString (buffer.js:803:11)
backend_1       |     at randomString (project/node_modules/tus-node-server/lib/models/StreamSplitter.js:7:37)
```

**Comment by tomgreco** [comment]
Looks like base64url is not part of the version of node I am running. 
The work around for this was to patch StreamSplitter.js

```
const base64url = require('base64url');

function randomString(size) {
    return base64url.toBase64(crypto.randomBytes(size)).slice(0, size);
}
```

**Comment by Murderlon** [comment]
Thanks for reporting. @tomgreco which version of Node are you running?

**Comment by tomgreco** [comment]
Using `ts-node` version 9 @Murderlon

**Comment by Murderlon** [comment]
`base64url` was a Node 15 feature (https://github.com/nodejs/node/pull/36952) but it was backported to Node 14. However, your version is a bit too old. It was backported to 14.18.0. Consider upgrading to that or ideally to latest LTS (16.15.0 at the time of writing).

I'm working towards tus-node-server@1.0.0 for which there will be official supported Node versions (`>14.18.0).

**Comment by tomgreco** [comment]
@Murderlon fair enough. Looking forward to more updates :)
