### ISSUE TITLE
Behind a load balacer

### ISSUE THREAD

**Issue by bekee** [tus/tus-node-server#398]
I've been struggling to run the application behind a load balancer. I keep getting this error
```

TypeError: this[method] is not a function
    at Object.isInvalidHeader (/var/www/html/node_modules/@tus/server/dist/validators/RequestValidator.js:75:28)
    at Server.handle (/var/www/html/node_modules/@tus/server/dist/server.js:113:53)
    at newFn (/var/www/html/node_modules/express-async-errors/index.js:16:20)
    at Layer.handle [as handle_request] (/var/www/html/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/node_modules/express/lib/router/route.js:144:13)
    at next (/var/www/html/node_modules/express/lib/router/route.js:140:7)
    at next (/var/www/html/node_modules/express/lib/router/route.js:140:7)
    at next (/var/www/html/node_modules/express/lib/router/route.js:140:7)
    at next (/var/www/html/node_modules/express/lib/router/route.js:140:7)
    at next (/var/www/html/node_modules/express/lib/router/route.js:140:7)
```

I'm using the express example which works well on my local
"@tus/server": "^1.0.0-beta.4",
@manelio @mitjap @kvz @Acconut

**Comment by bekee** [comment]
For those faced with similar issue using the plugin behind a load balancer, I had had use reverse proxy to to force enable  proto in the header via nginx
```

map $sent_http_content_type $expires {
    "text/html"                 epoch;
    "text/html; charset=utf-8"  epoch;
    default                     off;
}

server {
    listen          80;             # the port nginx is listening on
    server_name     _;    # setup your domain here

    gzip            on;
    gzip_types      text/plain application/xml text/css application/javascript;
    gzip_min_length 1000;

    location / {
        expires $expires;

        proxy_redirect                      off;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header proto              https;
        proxy_read_timeout          1m;
        proxy_connect_timeout       1m;
        proxy_pass                          http://nuxtjs:3000; # set the address of the Node.js instance here
    }
}
```

**Comment by bekee** [comment]
In addition, I enabled respectForwardedHeaders

`const serverUpload = new Server({path: '/files', datastore: store(), respectForwardedHeaders:true,   onUploadCreate: onUploadCreated,  onUploadFinish: onUploadFinished})`

**Comment by bekee** [comment]
In addition, I enabled respectForwardedHeaders
`
const serverUpload = new Server({path: '/files', datastore: store(), respectForwardedHeaders:true,   onUploadCreate: onUploadCreated,  onUploadFinish: onUploadFinished})
`

**Comment by Murderlon** [comment]
Thanks for all the details everyone. Glad it's resolved and indeed the server shouldn't crash anymore on headers. Further improved in #402.
