### ISSUE TITLE
Error: Cannot find module 'google-cloud' 

### ISSUE THREAD

**Issue by faridv** [tus/tus-node-server#56]
I can't run the server, nor demo files. I keep getting `Error: Cannot find module 'google-cloud'` from node.
Is there any workaround? Am I doing something wrong?

**Comment by kvz** [comment]
Refs https://github.com/tus/tusd/issues/68#issuecomment-256585287

Did you run npm install first?

If yes, might you happen to have a trace and/or more information regarding the conditions in which this error was triggered?

**Comment by faridv** [comment]
@kvz Install fails with following error:
`
node-pre-gyp ERR! Tried to download: https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v0.15.0/node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@0.15.0 and node@6.6.0 (node-v48 ABI) (falling back to source compile with node-gyp)
`

**Comment by bhstahl** [comment]
Hey @faridv, are you by any chance running this on windows? Would you mind trying `npm install --no-optional`?

**Comment by alolis** [comment]
I am experiencing the same problem after i upgraded to node `6.9.1`. I removed my node_modules and re-installed everything with `npm install` but no luck

**Comment by MonsieurLanza** [comment]
Same compilation issues here. Arch Linux up to date.

**Comment by Acconut** [comment]
> @MonsieurLanza I'm a bit pissed off since I really do not need google & s3 stuff. Is there a way to install without google & amazon stores ?

While not being a proper workaround, you should me able to manually clone the repository into the node_modules folder and then install the few required dependencies manually (https://github.com/tus/tus-node-server/blob/master/package.json#L55).

**Comment by MonsieurLanza** [comment]
Thanks. 
I forked and stripped all DataStore stuff except local file storage.
What bothers me is I will need to rely on npm for deployment. It would be great to ship external DataStores in separate packages, IMHO. 
The DataStore switching is really great, but somewhat overkill when all you need is local storage.

**Comment by MonsieurLanza** [comment]
By the way, here is a full log of what's happening. gprc dependency is failing to install. Compiles but link fails.

```
$ npm install --no-optional tus-node-server

> grpc@0.15.0 install /home/insert/some/path/node_modules/google-gax/node_modules/grpc
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v0.15.0/node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@0.15.0 and node@7.1.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
make : on entre dans le répertoire « /home/insert/some/path/node_modules/google-gax/node_modules/grpc/build »
  CC(target) Release/obj.target/grpc/src/core/lib/surface/init.o
  [... compilation goes OK ...]
  CC(target) Release/obj.target/gpr/src/core/lib/support/wrap_memcpy.o
  AR(target) Release/obj.target/libgpr.a
  COPY Release/libgpr.a
  CXX(target) Release/obj.target/grpc_node/src/node/ext/byte_buffer.o
../src/node/ext/byte_buffer.cc: Dans la fonction ‘v8::Local<v8::Value> grpc::node::MakeFastBuffer(v8::Local<v8::Value>)’:
../src/node/ext/byte_buffer.cc:96:72: attention : ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   Local<Object> fastBuffer = bufferConstructor->NewInstance(3, consArgs);
                                                                        ^
In file included from /home/lanza/.node-gyp/7.1.0/include/node/v8.h:26:0,
                 from /home/lanza/.node-gyp/7.1.0/include/node/node.h:42,
                 from ../src/node/ext/byte_buffer.cc:36:
/home/lanza/.node-gyp/7.1.0/include/node/v8.h:3288:31: note : declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/lanza/.node-gyp/7.1.0/include/node/v8config.h:329:3: note : in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CXX(target) Release/obj.target/grpc_node/src/node/ext/call.o
../src/node/ext/call.cc: Dans la fonction membre statique ‘static Nan::NAN_METHOD_RETURN_TYPE grpc::node::Call::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node/ext/call.cc:616:20: erreur : ‘class v8::Object’ has no member named ‘SetHiddenValue’; did you mean ‘IntegerValue’?
       info.This()->SetHiddenValue(Nan::New("channel_").ToLocalChecked(),
                    ^~~~~~~~~~~~~~
../src/node/ext/call.cc:625:19: attention : ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         argc, argv);
                   ^
In file included from /home/lanza/.node-gyp/7.1.0/include/node/v8.h:26:0,
                 from /home/lanza/.node-gyp/7.1.0/include/node/node.h:42,
                 from ../src/node/ext/call.cc:38:
/home/lanza/.node-gyp/7.1.0/include/node/v8.h:3288:31: note : declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/lanza/.node-gyp/7.1.0/include/node/v8config.h:329:3: note : in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [grpc_node.target.mk:132: Release/obj.target/grpc_node/src/node/ext/call.o] Error 1
make : on quitte le répertoire « /home/insert/some/path/node_modules/google-gax/node_modules/grpc/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.8.7-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/insert/some/path/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/insert/some/path/node_modules/google-gax/node_modules/grpc/src/node/extension_binary"
gyp ERR! cwd /home/insert/some/path/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/insert/some/path/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/home/insert/some/path/node_modules/google-gax/node_modules/grpc/src/node/extension_binary' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/insert/some/path/node_modules/google-gax/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.8.7-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/home/insert/some/path/node_modules/google-gax/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/insert/some/path/node_modules/google-gax/node_modules/grpc
node-pre-gyp ERR! node -v v7.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/insert/some/path/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/grpc_node.node --module_name=grpc_node --module_path=/home/insert/some/path/node_modules/google-gax/node_modules/grpc/src/node/extension_binary' (1)
lanza-photos@0.0.1 /home/insert/some/path
└── (empty)

npm WARN lanza-photos@0.0.1 No repository field.
npm WARN lanza-photos@0.0.1 No license field.
npm ERR! Linux 4.8.7-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "--no-optional" "tus-node-server"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! grpc@0.15.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@0.15.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grpc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grpc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grpc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/insert/some/path/npm-debug.log
npm ERR! code 1

```

**Comment by bhstahl** [comment]
Totally understand @MonsieurLanza and agree, I would be open to breaking the DataStore's out if others agree as well? I approached this with the intent to make it as easy as possible to get up and running quickly.

**Comment by bendiaz** [comment]
I have a similar issue with my VMware ubuntu 18.04 image. The command I'm using is
`sudo npm install --save @google-cloud/compute@0.7.1`
which doesn't install. When trying to kill an instance in node it always returns:
`Error: Cannot find module 'google-cloud/compute`

**Comment by Acconut** [comment]
Are you able to figure out why `@google-cloud/compute` is not installed for you? I think that's the most straightforward way to solve the problem.

**Comment by Murderlon** [comment]
The dependencies were recently updated to latest which very likely fixes this. If the issue persists, feel free to reopen.
