### ISSUE TITLE
grpc compile error

### ISSUE THREAD

**Issue by mhf-ir** [tus/tus-node-server#94]
I seems grpc compile error during latest version:

nodejs 8
ubuntu 16.04.3 (docker container)

installed via yarn 

```
module.js:540
    throw err;
    ^

Error: Cannot find module '/app/app/node_modules/@google-cloud/datastore/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/app/node_modules/@google-cloud/datastore/node_modules/grpc/src/grpc_extension.js:30:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

```

**Comment by bhstahl** [comment]
This should be closed with #90, ignoring the `@google-cloud/datastore` package
